Repository openshift/managed-upgrade-operator, pull requests merged in 2024-07, with the labels that each got.

#440 Osd 24234 use bound API token for prometheus-k8s in metric pkg
  build/Dockerfile
  build/Dockerfile.olm-registry
  hack/olm-registry/olm-artifacts-template.fedramp.yaml
  hack/olm-registry/olm-artifacts-template.yaml
  pkg/maintenance/alertmanagerMaintenance.go
  pkg/maintenance/maintenance_test.go
  pkg/metrics/metrics.go
  util/mocks/README.md
  util/mocks/cr-client.go
Labels: lgtm, approved

#441 Osd-23711 Refactor healthcheck servicelog
  pkg/eventmanager/eventmanager.go
  pkg/eventmanager/eventmanager_test.go
  pkg/eventmanager/mocks/eventmanager.go
  pkg/metrics/metrics.go
  pkg/metrics/mocks/metrics.go
  pkg/notifier/notifier.go
  pkg/notifier/ocmnotifier.go
  pkg/upgraders/healthcheck_alerts.go
  pkg/upgraders/healthcheck_alerts_test.go
  pkg/upgraders/healthcheck_clusteroperators.go
  pkg/upgraders/healthcheck_clusteroperators_test.go
  pkg/upgraders/healthcheck_nodes.go
  pkg/upgraders/healthcheck_nodes_test.go
  pkg/upgraders/healthcheckstep.go
  pkg/upgraders/healthcheckstep_test.go
Labels: lgtm, approved

#450 Updating boilerplate to v5.0.1
  .ci-operator.yaml
  boilerplate/_data/backing-image-tag
  boilerplate/_data/last-boilerplate-commit
  boilerplate/openshift/golang-osd-operator-osde2e/e2e-harness-generate.sh
  boilerplate/openshift/golang-osd-operator-osde2e/standard.mk
  boilerplate/openshift/golang-osd-operator-osde2e/test-harness-template.yml
  boilerplate/openshift/golang-osd-operator/csv-generate/csv-generate.sh
  boilerplate/openshift/golang-osd-operator/ensure.sh
  boilerplate/openshift/golang-osd-operator/golangci.yml
  boilerplate/openshift/golang-osd-operator/project.mk
  boilerplate/openshift/golang-osd-operator/rvmo-bundle.sh
  boilerplate/openshift/golang-osd-operator/standard.mk
  build/Dockerfile
  deploy/crds/upgrade.managed.openshift.io_upgradeconfigs.yaml
  pkg/collector/collector.go
  pkg/drain/stuckTerminatingStrategy_test.go
  pkg/metrics/metrics.go
  pkg/upgraders/maintenancestep.go
  pkg/upgraders/postupgradestep.go
Labels: lgtm, approved

#444 Adding the ability to configure SL severity
  pkg/notifier/ocmnotifier.go
  pkg/ocm/client.go
  pkg/ocmagent/client.go
Labels: lgtm, approved

#449 Adding featuregate for PreHealthCheck
  api/v1alpha1/upgradeconfig_types.go
  controllers/upgradeconfig/config.go
  controllers/upgradeconfig/upgradeconfig_controller.go
  controllers/upgradeconfig/upgradeconfig_controller_test.go
  docs/configmap.md
Labels: lgtm, approved, tide/merge-method-squash

#445 PDB HealthCheck Implementation
  controllers/upgradeconfig/upgradeconfig_controller.go
  controllers/upgradeconfig/upgradeconfig_controller_test.go
  hack/olm-registry/olm-artifacts-template.fedramp.yaml
  hack/olm-registry/olm-artifacts-template.yaml
  main.go
  mocks/builder.go
  mocks/client.go
  pkg/dvo/builder.go
  pkg/dvo/client.go
  pkg/dvo/mocks/builder.go
  pkg/dvo/mocks/client.go
  pkg/metrics/metrics.go
  pkg/upgraders/healthcheck_pdb.go
  pkg/upgraders/healthcheckstep.go
  pkg/upgraders/healthcheckstep_test.go
  pkg/upgraders/osdupgrader.go
  pkg/upgraders/upgrader.go
  test/deploy/dvo-networkpolicy.yaml
  test/deploy/dvo-reader-rolebinding.yaml
  test/deploy/dvo-role.yaml
Labels: lgtm, approved, tide/merge-method-squash

#452 OSD-24706: Adding test file for ocmprovider's config
  pkg/ocmprovider/config_test.go
Labels: lgtm, approved, jira/valid-reference

#454 Adding ServiceLogNotification featureGate for controlling notifications
  api/v1alpha1/upgradeconfig_types.go
  docs/configmap.md
  pkg/notifier/notifier.go
  pkg/notifier/ocmconfig.go
  pkg/notifier/ocmnotifier.go
Labels: lgtm, approved

#455 bugfix: Add validation for IntorString in health check
  pkg/dvo/builder.go
  pkg/upgraders/healthcheck_pdb.go
  pkg/upgraders/healthcheckstep_test.go
Labels: lgtm, approved

#438 Reset the NodeDrainFailed metric when the node deletion timestamp is set
  controllers/nodekeeper/nodekeeper_controller.go
  controllers/nodekeeper/nodekeeper_controller_test.go
Labels: lgtm, approved
