Repository openshift/managed-upgrade-operator, pull requests merged in 2024-06, with the labels that each got.

#428 No worker machinepool HealthCheck
  pkg/eventmanager/eventmanager.go
  pkg/metrics/metrics.go
  pkg/notifier/notifier.go
  pkg/notifier/ocmnotifier.go
  pkg/upgraders/healthcheckstep.go
  pkg/upgraders/healthcheckstep_test.go
  pkg/upgraders/notifierstep.go
  pkg/upgraders/notifierstep_test.go
  pkg/upgraders/scalerstep.go
  pkg/upgraders/scalerstep_test.go
Labels: lgtm, approved

#429 go.mod: go get github.com/openshift/osde2e-common@latest
  go.mod
  go.sum
Labels: lgtm, approved

#430 go.mod go get github.com/openshift/api@release-4.16
  go.mod
  go.sum
Labels: lgtm, approved

#426 Integrating Pre-HealthCheck with UpgradeConfig controller
  api/v1alpha1/upgradeconfig_types.go
  controllers/upgradeconfig/upgradeconfig_controller.go
  controllers/upgradeconfig/upgradeconfig_controller_test.go
  deploy/crds/upgrade.managed.openshift.io_upgradeconfigs.yaml
  docs/controllers/upgradeconfig.md
  pkg/upgraders/aroupgrader.go
  pkg/upgraders/builder.go
  pkg/upgraders/mocks/cluster_upgrader.go
  pkg/upgraders/osdupgrader.go
Labels: lgtm, approved

#431 Updating boilerplate to fix MUO builds
  boilerplate/_data/last-boilerplate-commit
  boilerplate/openshift/golang-osd-operator-osde2e/e2e-harness-generate.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/catalog-publish.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/csv-generate.sh
Labels: lgtm, approved

#433 Removing HealthCheckDuration spec field
  api/v1alpha1/upgradeconfig_types.go
  build/Dockerfile
  build/Dockerfile.olm-registry
  deploy/crds/upgrade.managed.openshift.io_upgradeconfigs.yaml
  docs/controllers/upgradeconfig.md
Labels: lgtm, approved

#432 Osd 22457 add manual cordon node check
  pkg/metrics/metrics.go
  pkg/upgraders/healthcheck_nodes.go
  pkg/upgraders/healthcheck_nodes_test.go
  pkg/upgraders/healthcheckstep.go
  pkg/upgraders/healthcheckstep_test.go
Labels: lgtm, approved, tide/merge-method-squash

#436 OSD-24044 Fix log format bug
  pkg/upgraders/healthcheck_clusteroperators.go
Labels: lgtm, approved

#435 OSD-23983: Updating boilerplate
  boilerplate/_data/last-boilerplate-commit
  boilerplate/openshift/golang-osd-operator/csv-generate/csv-generate.sh
  boilerplate/openshift/golang-osd-operator/project.mk
  boilerplate/openshift/golang-osd-operator/rvmo-bundle.sh
Labels: lgtm, approved, jira/valid-reference

#434 OSD-23984 Add node unschedulable taint check
  docs/testing.md
  pkg/machinery/machinery.go
  pkg/machinery/machinery_test.go
  pkg/machinery/mocks/machinery.go
  pkg/machinery/node.go
  pkg/metrics/metrics.go
  pkg/upgraders/healthcheck_nodes.go
  pkg/upgraders/healthcheckstep.go
  pkg/upgraders/healthcheckstep_test.go
Labels: lgtm, approved

#439 Enabling ServiceLog messages for Upgrade phases
  go.mod
  go.sum
  pkg/eventmanager/eventmanager.go
  pkg/notifier/notifier.go
  pkg/notifier/ocmnotifier.go
  pkg/ocm/builder.go
  pkg/ocm/client.go
  pkg/ocm/mocks/client.go
  pkg/ocmagent/builder.go
  pkg/ocmagent/client.go
  pkg/ocmprovider/ocmprovider.go
  pkg/upgraders/controlplanestep.go
  pkg/upgraders/controlplanestep_test.go
  pkg/upgraders/notifierstep.go
  pkg/upgraders/workerstep.go
  pkg/upgraders/workerstep_test.go
Labels: lgtm, approved
