Repository openshift/managed-upgrade-operator, pull requests merged in 2024-08, with the labels that each got.

#461 revert the changes in fedramp rbac which causes problem
  hack/olm-registry/olm-artifacts-template.fedramp.yaml
Labels: lgtm, approved

#462 chore: Update OWNERS file with new reviewers
  OWNERS
Labels: lgtm, approved

#464 Add logger for capacityreservation and pdb healthcheck success
  pkg/upgraders/healthcheck_pdb.go
  pkg/upgraders/healthcheckstep.go
Labels: lgtm, approved

#465 Updating tests for UpgradeConfig controller relevant to PreHealthCheck work
  controllers/upgradeconfig/upgradeconfig_controller_test.go
Labels: lgtm, approved

#447 OSD-23975 add version and state in the health-check metrics
  docs/metrics.md
  pkg/metrics/metrics.go
  pkg/metrics/mocks/metrics.go
  pkg/upgraders/healthcheck_alerts.go
  pkg/upgraders/healthcheck_alerts_test.go
  pkg/upgraders/healthcheck_clusteroperators.go
  pkg/upgraders/healthcheck_clusteroperators_test.go
  pkg/upgraders/healthcheck_nodes.go
  pkg/upgraders/healthcheck_nodes_test.go
  pkg/upgraders/healthcheck_pdb.go
  pkg/upgraders/healthcheckstep.go
  pkg/upgraders/healthcheckstep_test.go
Labels: lgtm, approved

#466 Make no worker machinepool PHC as non-failing
  pkg/upgraders/healthcheckstep.go
  pkg/upgraders/healthcheckstep_test.go
Labels: lgtm, approved

#458 OSD-24723 unit testcases for code under /pkg/ocm/
  pkg/ocm/client_test.go
  pkg/ocm/config_test.go
  pkg/scaler/scaling_test.go
  pkg/upgraders/healthcheck_nodes_test.go
Labels: lgtm, approved

#459 OSD-24722: Adding unit test case
  pkg/notifier/config_test.go
  pkg/notifier/lognotifier_test.go
  pkg/notifier/ocmconfig_test.go
  pkg/upgraders/healthcheckstep_test.go
Labels: lgtm, approved, jira/valid-reference

#463 OSD-24706: PHC unit test case
  pkg/upgraders/healthcheck_pdb_test.go
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#467 Adding more tests around upgrade notifications
  boilerplate/_data/last-boilerplate-commit
  boilerplate/openshift/golang-osd-operator/build-opm-catalog.sh
  build/Dockerfile
  build/Dockerfile.olm-registry
  pkg/ocmprovider/ocmprovider_test.go
  pkg/upgraders/controlplanestep_test.go
  pkg/upgraders/notifierstep_test.go
  pkg/upgraders/workerstep.go
  pkg/upgraders/workerstep_test.go
Labels: lgtm, approved

#468 Healthcheck return false only for CriticalAlerts and ClusterOperators
  pkg/upgraders/healthcheckstep.go
Labels: lgtm, approved

#453 Send informational service log to customers about node drain grace time
  pkg/drain/nodeDrainStrategy.go
  pkg/drain/osd_drain_strategy_test.go
  pkg/drain/strategy.go
Labels: lgtm, approved

#469 Adding KCS link to healthcheck SLs
  pkg/notifier/ocmnotifier.go
  pkg/ocm/client.go
Labels: lgtm, approved

#471 Updating PHC descriptions
  pkg/notifier/ocmnotifier.go
Labels: lgtm, approved

#473 Updating boilerplate
  OWNERS_ALIASES
  boilerplate/_data/last-boilerplate-commit
  boilerplate/openshift/golang-osd-operator/OWNERS_ALIASES
  build/Dockerfile
  build/Dockerfile.olm-registry
Labels: lgtm, approved
